### PR TITLE
Apollo Server v4 support

### PR DESCRIPTION
**Pull request by AnotherGitProfile**
Migrate to graphql v16 and apollo server v4 according to this guide https://www.apollographql.com/docs/apollo-server/migration. But I couldn't implement `getApolloServerVersion` because `@apollo/server` package doesn't export package.json.

https://github.com/bfmatei/apollo-prometheus-exporter/issues/42

### CODE REVIEW

**Comment by tiagodj** [comment]
Have you considered doing:

```TypeScript
const apolloPackageJson = require("@apollo/server/package.json");

console.log(apolloPackageJson.version);
// prints 4.3.0
```

**Comment by AnotherGitProfile** [comment]
When I try to run it with `node` or `ts-node` I get the same error
```
> require('@apollo/server/package.json')
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in ...
```
As defined in file [package.json](https://github.com/apollographql/apollo-server/blob/main/packages/server/package.json) for @apollo/server this file is not exported and cannot be imported directly

**Comment by tiagodj** [comment]
You added the `@apollo/server` dev dependency for the `package.json` here. 

There's a version number there. Would it be ok to infer the version from it?

```json
{
   "@apollo/server": "^4.0.2",
}
```

**Comment by tiagodj** [comment]
@bfmatei any thoughts on this?

**Comment by febarbosa182** [comment]
Each major version of this project supports a major version from apollo server project. Should this PR result in a 3.x version?

**Comment by tiagodj** [comment]
@rgeyer @tomwilkie anything else we can help with to get this PR approved/merged?

**Review by imwexpex — APPROVED** [review]

**Comment by vfiset** [comment]
Thanks @imwexpex for the review 👍  @rgeyer @tomwilkie anything else we can help with to get this PR merged?

**Comment by glensc** [comment]
Have you tried requesting exporting version or `packages.json` from `@apollo/server`. I think it's trivial do do so.

**Comment by febarbosa182** [comment]
Apollo server 2 and 3 are getting close to EOF, see the [announcement](https://www.apollographql.com/blog/announcement/backend/announcing-the-end-of-life-schedule-for-apollo-server-2-3/)
Is there anything else we can help with to get this PR approved/merged?

**Comment by vfiset** [comment]
Hi  @rgeyer @tomwilkie, is it a good time to get this PR merged ?

**Comment by tomwilkie** [comment]
Hi @vfiset; I'm not a maintainer on this repo, I think you mean to ask @bfmatei

**Comment by vfiset** [comment]
I am sorry @tomwilkie !

**Comment by rgeyer** [comment]
I also was not a maintainer on this repo.. Until today.

Doing one final sanity check pass on this, and trying to recruit some help since I don't know TypeScript very well at all. We'll get this merged ASAP tho. Thanks for your patience!

**Comment by neodem** [comment]
Hi. Thanks so much for doing this work.. Excited to see the new release!!

**Comment by neodem** [comment]
Hi @rgeyer I'm wondering if you're still working on this PR? I recently moved to apollo v4 and I kind of depend on this plugin.. Just curious.. thanks

**Comment by rgeyer** [comment]
> Hi @rgeyer I'm wondering if you're still working on this PR? I recently moved to apollo v4 and I kind of depend on this plugin.. Just curious.. thanks

Heya! I've gone ahead and merged. As stated before, I'm no Typescript expert, but it "looks fine" to me.

I'll keep an eye out in case anyone encounters issues!

**Comment by neodem** [comment]
awesome news.. thank you! 

Any idea when the release will get cut? There's not much insight into the build/ci process for this project.

**Comment by rgeyer** [comment]
Yeah, that was my next question, namely, how do you consume this. Looks like it'll have to be built and deployed to NPM?

Looks from the CD process that the NPM token is expired or invalidated. I'll have to look into creating a new one.

You'll have to be patient as I learn how to do CI for a javascript/typescript project 😩 😄

**Comment by neodem** [comment]
Thank you so much! No worries.. it takes as long as it takes! :)

**Comment by tiagodj** [comment]
The release build is failing because the token to authenticate with NPM and publish the package is invalid (probably expired).

```
[4:35:37 PM] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry [https://registry.npmjs.org/.](https://registry.npmjs.org/)
```

Someone with permission to do that need to update the token in the pipeline env variables.

**Comment by neodem** [comment]
Any luck getting this built?

v

**Comment by glensc** [comment]
@bfmatei so can you refresh npm token, so new maintainers can make release?

**Comment by lawrentiy** [comment]
I'm all waiting.
Thanx a lot!

**Comment by neodem** [comment]
Is there any hope that a release will get built with this change in it?

**Comment by vfiset** [comment]
Hi @rgeyer ! I've never used `semantic-release` myself but looking at the doc and github issue I think the problem is that the [commit](https://github.com/bfmatei/apollo-prometheus-exporter/commits/main) message from September 13th does not respect the naming convention. The message is currently `Merge pull request #43 from AnotherGitProfile/apollo-4` and it should be something like `feat() Apollo Server v4 support`. That way it will be picked up.

**Comment by vfiset** [comment]
from the doc:
> By default, semantic-release uses [Angular Commit Message Conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format). The commit message format can be changed with the [preset or config options](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#options) of the [@semantic-release/commit-analyzer](https://github.com/semantic-release/commit-analyzer#options) and [@semantic-release/release-notes-generator](https://github.com/semantic-release/release-notes-generator#options) plugins.

AFAIK there is no config options in `bfmatei/apollo-prometheus-exporter` so [Angular Commit Message Conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format) is used.

**Comment by rgeyer** [comment]
> Hi @rgeyer ! I've never used `semantic-release` myself but looking at the doc and github issues I think the problem is that the [commit](https://github.com/bfmatei/apollo-prometheus-exporter/commits/main) message from September 13th does not respect the naming convention. The message is currently `Merge pull request #43 from AnotherGitProfile/apollo-4` and it should be something like `feat() Apollo Server v4 support`. That way it will be picked up.

Yes, this seems to be what I'm able to determine from the docs as well. I was finally able to find, and grok them!

I'll see if rewriting those commit messages will work. I may have to rewrite them, and run the release manually. Time will tell.

Thank you for the feedback!

**Comment by rgeyer** [comment]
Well, we have a successful NPM release, but it seems there are permissions issues with the github token, and a release against the repo wasn't possible.

Progress, at least!

**Comment by vfiset** [comment]
@bfmatei any chance you can @rgeyer with the final step [here](https://github.com/bfmatei/apollo-prometheus-exporter/pull/43#issuecomment-1823463372) ?

**Comment by gravelg** [comment]
@vfiset version 3.0.0 has been available in the npm repos for a few months already, this should be all resolved.

You can use the package even if the github release is not available yet.

**Comment by vfiset** [comment]
OMG I relied solely on this thread to watch the release instead of also checking the actual release page 🤦 Merci @gravelg !

**Comment by rgeyer** [comment]
Apologies for any confusion @vfiset.

I was going to ask if you absolutely needed the github release (I can do one manually, tho the automation still seems borked), in addition to the NPM release.

Hopefully the next update/release will work in both places without too much drama. 😂

**Comment by vfiset** [comment]
No worries @rgeyer, thanks again for your work. And for the record, NPM release is fine !

**Comment by glensc** [comment]
Can https://github.com/bfmatei/apollo-prometheus-exporter/issues/42 be closed then?

**Pull request merged**
